import { FoodItem } from '@/types/food';

export const FOOD_DATABASE: FoodItem[] = [

  // ── Proteins (generic) ────────────────────────────────────────────────────
  { id: 'f1',  name: 'Chicken Breast (grilled)', servingSize: 100, servingUnit: 'g', imageQuery: 'grilled chicken breast', nutrients: { calories: 165, protein: 31, carbs: 0,    fat: 3.6, fiber: 0 } },
  { id: 'f2',  name: 'Eggs (whole, boiled)',      servingSize: 50,  servingUnit: 'g', imageQuery: 'boiled eggs',           nutrients: { calories: 78,  protein: 6,  carbs: 0.6,  fat: 5,   fiber: 0 } },
  { id: 'f3',  name: 'Salmon (baked)',             servingSize: 100, servingUnit: 'g', imageQuery: 'baked salmon',          nutrients: { calories: 208, protein: 20, carbs: 0,    fat: 13,  fiber: 0 } },
  { id: 'f5',  name: 'Greek Yogurt (plain)',       servingSize: 150, servingUnit: 'g', imageQuery: 'greek yogurt',          nutrients: { calories: 100, protein: 17, carbs: 6,    fat: 0.7, fiber: 0 } },
  { id: 'f6',  name: 'Whey Protein Shake',         servingSize: 30,  servingUnit: 'g', imageQuery: 'protein shake',         nutrients: { calories: 120, protein: 24, carbs: 3,    fat: 1.5, fiber: 0 } },
  { id: 'f8',  name: 'Tofu (firm)',                servingSize: 100, servingUnit: 'g', imageQuery: 'tofu',                  nutrients: { calories: 144, protein: 17, carbs: 3,    fat: 8,   fiber: 2 } },

  // ── Indian Dairy & Paneer ─────────────────────────────────────────────────
  { id: 'id1',  name: 'Paneer',                   servingSize: 100, servingUnit: 'g', imageQuery: 'indian paneer cheese',     nutrients: { calories: 265, protein: 18, carbs: 1.2, fat: 21,  fiber: 0 } },
  { id: 'id2',  name: 'Dahi (Curd)',               servingSize: 200, servingUnit: 'g', imageQuery: 'indian curd dahi',         nutrients: { calories: 118, protein: 8,  carbs: 9,   fat: 4,   fiber: 0 } },
  { id: 'id3',  name: 'Lassi (Sweet)',             servingSize: 250, servingUnit: 'ml',imageQuery: 'sweet lassi drink india',  nutrients: { calories: 190, protein: 7,  carbs: 28,  fat: 5,   fiber: 0 } },
  { id: 'id4',  name: 'Lassi (Salted / Chaas)',    servingSize: 250, servingUnit: 'ml',imageQuery: 'chaas buttermilk india',   nutrients: { calories: 80,  protein: 4,  carbs: 8,   fat: 2,   fiber: 0 } },
  { id: 'id5',  name: 'Milk (Full Fat, Indian)',   servingSize: 240, servingUnit: 'ml',imageQuery: 'glass of milk',            nutrients: { calories: 150, protein: 8,  carbs: 12,  fat: 8,   fiber: 0 } },
  { id: 'id6',  name: 'Ghee',                      servingSize: 10,  servingUnit: 'g', imageQuery: 'ghee clarified butter',    nutrients: { calories: 90,  protein: 0,  carbs: 0,   fat: 10,  fiber: 0 } },
  { id: 'id7',  name: 'Khoa / Mawa',               servingSize: 50,  servingUnit: 'g', imageQuery: 'khoa mawa indian sweet',   nutrients: { calories: 215, protein: 8,  carbs: 20,  fat: 11,  fiber: 0 } },
  { id: 'id8',  name: 'Raita (Cucumber)',          servingSize: 150, servingUnit: 'g', imageQuery: 'cucumber raita indian',    nutrients: { calories: 72,  protein: 4,  carbs: 7,   fat: 2.5, fiber: 0.5 } },
  { id: 'id9',  name: 'Masala Chai (with milk)',   servingSize: 200, servingUnit: 'ml',imageQuery: 'masala chai tea india',    nutrients: { calories: 80,  protein: 2,  carbs: 10,  fat: 3,   fiber: 0 } },
  { id: 'id10', name: 'Haldi Doodh (Turmeric Milk)',servingSize: 200,servingUnit: 'ml',imageQuery: 'turmeric golden milk',    nutrients: { calories: 120, protein: 5,  carbs: 11,  fat: 5,   fiber: 0 } },

  // ── Indian Breakfast ──────────────────────────────────────────────────────
  { id: 'ib1',  name: 'Idli (plain, 2 pieces)',     servingSize: 100, servingUnit: 'g', imageQuery: 'idli sambar south india',     nutrients: { calories: 116, protein: 4,  carbs: 23,  fat: 1,   fiber: 1.5 } },
  { id: 'ib2',  name: 'Dosa (plain)',                servingSize: 100, servingUnit: 'g', imageQuery: 'plain dosa south indian',     nutrients: { calories: 168, protein: 4,  carbs: 30,  fat: 4,   fiber: 2 } },
  { id: 'ib3',  name: 'Masala Dosa',                 servingSize: 200, servingUnit: 'g', imageQuery: 'masala dosa indian breakfast', nutrients: { calories: 340, protein: 7,  carbs: 54,  fat: 10,  fiber: 3 } },
  { id: 'ib4',  name: 'Rava Dosa',                   servingSize: 120, servingUnit: 'g', imageQuery: 'rava dosa crispy',            nutrients: { calories: 215, protein: 5,  carbs: 35,  fat: 7,   fiber: 1.5 } },
  { id: 'ib5',  name: 'Uttapam',                     servingSize: 150, servingUnit: 'g', imageQuery: 'uttapam vegetable indian',    nutrients: { calories: 210, protein: 6,  carbs: 36,  fat: 5,   fiber: 2 } },
  { id: 'ib6',  name: 'Medu Vada (2 pieces)',        servingSize: 100, servingUnit: 'g', imageQuery: 'medu vada south indian',      nutrients: { calories: 260, protein: 8,  carbs: 30,  fat: 12,  fiber: 3 } },
  { id: 'ib7',  name: 'Sambhar',                     servingSize: 200, servingUnit: 'ml',imageQuery: 'sambhar lentil soup',         nutrients: { calories: 80,  protein: 4,  carbs: 12,  fat: 1.5, fiber: 3 } },
  { id: 'ib8',  name: 'Poha',                        servingSize: 150, servingUnit: 'g', imageQuery: 'poha flattened rice india',   nutrients: { calories: 250, protein: 5,  carbs: 47,  fat: 5,   fiber: 3 } },
  { id: 'ib9',  name: 'Upma',                        servingSize: 200, servingUnit: 'g', imageQuery: 'upma semolina india',         nutrients: { calories: 220, protein: 5,  carbs: 38,  fat: 6,   fiber: 3 } },
  { id: 'ib10', name: 'Dhokla',                      servingSize: 100, servingUnit: 'g', imageQuery: 'dhokla gujarati snack',       nutrients: { calories: 160, protein: 6,  carbs: 27,  fat: 3.5, fiber: 2 } },
  { id: 'ib11', name: 'Besan Chilla',                servingSize: 150, servingUnit: 'g', imageQuery: 'besan chilla pancake india',  nutrients: { calories: 230, protein: 10, carbs: 30,  fat: 8,   fiber: 4 } },
  { id: 'ib12', name: 'Moong Dal Chilla',            servingSize: 150, servingUnit: 'g', imageQuery: 'moong dal chilla',            nutrients: { calories: 210, protein: 12, carbs: 28,  fat: 6,   fiber: 4 } },
  { id: 'ib13', name: 'Aloo Paratha',                servingSize: 120, servingUnit: 'g', imageQuery: 'aloo paratha stuffed bread',  nutrients: { calories: 310, protein: 7,  carbs: 48,  fat: 10,  fiber: 3 } },
  { id: 'ib14', name: 'Gobi Paratha',                servingSize: 120, servingUnit: 'g', imageQuery: 'gobi paratha cauliflower',   nutrients: { calories: 285, protein: 7,  carbs: 44,  fat: 9,   fiber: 3.5 } },
  { id: 'ib15', name: 'Methi Paratha',               servingSize: 100, servingUnit: 'g', imageQuery: 'methi paratha fenugreek',    nutrients: { calories: 270, protein: 7,  carbs: 42,  fat: 9,   fiber: 4 } },
  { id: 'ib16', name: 'Paneer Paratha',              servingSize: 120, servingUnit: 'g', imageQuery: 'paneer paratha indian bread', nutrients: { calories: 340, protein: 12, carbs: 42,  fat: 14,  fiber: 2.5 } },
  { id: 'ib17', name: 'Thepla',                      servingSize: 80,  servingUnit: 'g', imageQuery: 'thepla gujarati flatbread',  nutrients: { calories: 240, protein: 6,  carbs: 35,  fat: 8,   fiber: 3 } },
  { id: 'ib18', name: 'Sabudana Khichdi',            servingSize: 200, servingUnit: 'g', imageQuery: 'sabudana khichdi tapioca',   nutrients: { calories: 340, protein: 4,  carbs: 62,  fat: 8,   fiber: 1 } },
  { id: 'ib19', name: 'Rava / Sooji Upma',           servingSize: 200, servingUnit: 'g', imageQuery: 'sooji upma semolina',        nutrients: { calories: 215, protein: 5,  carbs: 37,  fat: 5.5, fiber: 2 } },
  { id: 'ib20', name: 'Oats Upma (Indian style)',    servingSize: 200, servingUnit: 'g', imageQuery: 'oats upma indian healthy',   nutrients: { calories: 190, protein: 6,  carbs: 30,  fat: 5,   fiber: 5 } },

  // ── Rice Dishes ───────────────────────────────────────────────────────────
  { id: 'ir1',  name: 'Steamed Basmati Rice',        servingSize: 150, servingUnit: 'g', imageQuery: 'basmati rice cooked',         nutrients: { calories: 195, protein: 4,  carbs: 43,  fat: 0.4, fiber: 0.6 } },
  { id: 'ir2',  name: 'Jeera Rice',                  servingSize: 150, servingUnit: 'g', imageQuery: 'jeera rice cumin',            nutrients: { calories: 220, protein: 4,  carbs: 44,  fat: 3,   fiber: 0.6 } },
  { id: 'ir3',  name: 'Veg Biryani',                 servingSize: 250, servingUnit: 'g', imageQuery: 'veg biryani indian rice',     nutrients: { calories: 350, protein: 8,  carbs: 62,  fat: 8,   fiber: 4 } },
  { id: 'ir4',  name: 'Chicken Biryani',             servingSize: 300, servingUnit: 'g', imageQuery: 'chicken biryani spicy rice',  nutrients: { calories: 480, protein: 25, carbs: 60,  fat: 14,  fiber: 3 } },
  { id: 'ir5',  name: 'Mutton Biryani',              servingSize: 300, servingUnit: 'g', imageQuery: 'mutton biryani hyderabadi',   nutrients: { calories: 530, protein: 26, carbs: 58,  fat: 18,  fiber: 3 } },
  { id: 'ir6',  name: 'Egg Biryani',                 servingSize: 280, servingUnit: 'g', imageQuery: 'egg biryani indian',          nutrients: { calories: 420, protein: 16, carbs: 58,  fat: 12,  fiber: 2.5 } },
  { id: 'ir7',  name: 'Khichdi',                     servingSize: 250, servingUnit: 'g', imageQuery: 'khichdi rice lentil india',   nutrients: { calories: 280, protein: 10, carbs: 50,  fat: 4,   fiber: 5 } },
  { id: 'ir8',  name: 'Curd Rice',                   servingSize: 200, servingUnit: 'g', imageQuery: 'curd rice south india',       nutrients: { calories: 220, protein: 7,  carbs: 38,  fat: 4,   fiber: 1 } },
  { id: 'ir9',  name: 'Lemon Rice',                  servingSize: 200, servingUnit: 'g', imageQuery: 'lemon rice south indian',     nutrients: { calories: 240, protein: 4,  carbs: 44,  fat: 5,   fiber: 1.5 } },
  { id: 'ir10', name: 'Tomato Rice',                 servingSize: 200, servingUnit: 'g', imageQuery: 'tomato rice spicy india',     nutrients: { calories: 230, protein: 4,  carbs: 43,  fat: 4,   fiber: 2 } },
  { id: 'ir11', name: 'Peas Pulao (Matar Pulao)',    servingSize: 200, servingUnit: 'g', imageQuery: 'matar pulao peas rice',       nutrients: { calories: 260, protein: 6,  carbs: 48,  fat: 4.5, fiber: 3 } },
  { id: 'ir12', name: 'Brown Rice (cooked)',          servingSize: 150, servingUnit: 'g', imageQuery: 'brown rice healthy',          nutrients: { calories: 170, protein: 4,  carbs: 36,  fat: 1.5, fiber: 2.5 } },

  // ── Dals & Legumes ────────────────────────────────────────────────────────
  { id: 'dl1',  name: 'Toor Dal (Arhar, cooked)',    servingSize: 200, servingUnit: 'g', imageQuery: 'toor dal lentil soup india',  nutrients: { calories: 200, protein: 12, carbs: 32,  fat: 2,   fiber: 8 } },
  { id: 'dl2',  name: 'Moong Dal (Yellow, cooked)',  servingSize: 200, servingUnit: 'g', imageQuery: 'moong dal yellow soup',       nutrients: { calories: 170, protein: 11, carbs: 28,  fat: 1,   fiber: 7 } },
  { id: 'dl3',  name: 'Masoor Dal (Red Lentil)',     servingSize: 200, servingUnit: 'g', imageQuery: 'masoor dal red lentil',       nutrients: { calories: 185, protein: 12, carbs: 30,  fat: 1,   fiber: 8 } },
  { id: 'dl4',  name: 'Chana Dal (cooked)',          servingSize: 200, servingUnit: 'g', imageQuery: 'chana dal bengal gram',       nutrients: { calories: 220, protein: 13, carbs: 36,  fat: 2,   fiber: 9 } },
  { id: 'dl5',  name: 'Urad Dal (Black Lentil)',     servingSize: 200, servingUnit: 'g', imageQuery: 'urad dal black lentil',       nutrients: { calories: 210, protein: 13, carbs: 33,  fat: 1.5, fiber: 8 } },
  { id: 'dl6',  name: 'Dal Makhani',                 servingSize: 200, servingUnit: 'g', imageQuery: 'dal makhani creamy black',    nutrients: { calories: 295, protein: 13, carbs: 32,  fat: 13,  fiber: 8 } },
  { id: 'dl7',  name: 'Dal Tadka',                   servingSize: 200, servingUnit: 'g', imageQuery: 'dal tadka yellow tempered',   nutrients: { calories: 195, protein: 11, carbs: 28,  fat: 5,   fiber: 7 } },
  { id: 'dl8',  name: 'Rajma (Kidney Beans curry)',  servingSize: 200, servingUnit: 'g', imageQuery: 'rajma kidney beans curry',    nutrients: { calories: 230, protein: 13, carbs: 36,  fat: 4,   fiber: 9 } },
  { id: 'dl9',  name: 'Chole (Chickpea curry)',      servingSize: 200, servingUnit: 'g', imageQuery: 'chole chickpea curry india',  nutrients: { calories: 240, protein: 12, carbs: 38,  fat: 5,   fiber: 10 } },
  { id: 'dl10', name: 'Whole Moong (cooked)',        servingSize: 200, servingUnit: 'g', imageQuery: 'whole moong green dal',       nutrients: { calories: 190, protein: 13, carbs: 30,  fat: 1,   fiber: 8 } },
  { id: 'dl11', name: 'Panchmel Dal',                servingSize: 200, servingUnit: 'g', imageQuery: 'panchmel dal five lentils',   nutrients: { calories: 205, protein: 12, carbs: 32,  fat: 3,   fiber: 8.5 } },
  { id: 'dl12', name: 'Sambar',                      servingSize: 200, servingUnit: 'g', imageQuery: 'sambar vegetable lentil',     nutrients: { calories: 85,  protein: 4,  carbs: 13,  fat: 1.5, fiber: 3 } },

  // ── Indian Breads ─────────────────────────────────────────────────────────
  { id: 'ibr1', name: 'Roti / Chapati',              servingSize: 40,  servingUnit: 'g', imageQuery: 'roti chapati whole wheat',    nutrients: { calories: 120, protein: 3,  carbs: 18,  fat: 3.7, fiber: 2 } },
  { id: 'ibr2', name: 'Paratha (plain)',              servingSize: 60,  servingUnit: 'g', imageQuery: 'plain paratha indian',        nutrients: { calories: 200, protein: 4,  carbs: 26,  fat: 9,   fiber: 2 } },
  { id: 'ibr3', name: 'Naan',                        servingSize: 90,  servingUnit: 'g', imageQuery: 'naan indian bread tandoor',   nutrients: { calories: 262, protein: 8,  carbs: 45,  fat: 5,   fiber: 2 } },
  { id: 'ibr4', name: 'Bhatura',                     servingSize: 80,  servingUnit: 'g', imageQuery: 'bhatura fried bread india',   nutrients: { calories: 300, protein: 7,  carbs: 44,  fat: 11,  fiber: 1.5 } },
  { id: 'ibr5', name: 'Puri (2 pieces)',             servingSize: 60,  servingUnit: 'g', imageQuery: 'puri fried bread india',      nutrients: { calories: 220, protein: 4,  carbs: 28,  fat: 10,  fiber: 1.5 } },
  { id: 'ibr6', name: 'Tandoori Roti',               servingSize: 50,  servingUnit: 'g', imageQuery: 'tandoori roti bread',         nutrients: { calories: 140, protein: 4,  carbs: 27,  fat: 2,   fiber: 2.5 } },
  { id: 'ibr7', name: 'Missi Roti',                  servingSize: 60,  servingUnit: 'g', imageQuery: 'missi roti besan bread',      nutrients: { calories: 170, protein: 6,  carbs: 27,  fat: 4,   fiber: 3 } },

  // ── Vegetable Curries (Sabzi) ─────────────────────────────────────────────
  { id: 'iv1',  name: 'Aloo Gobi',                   servingSize: 200, servingUnit: 'g', imageQuery: 'aloo gobi potato cauliflower',nutrients: { calories: 190, protein: 5,  carbs: 30,  fat: 6,   fiber: 5 } },
  { id: 'iv2',  name: 'Aloo Matar',                  servingSize: 200, servingUnit: 'g', imageQuery: 'aloo matar peas curry',       nutrients: { calories: 200, protein: 6,  carbs: 34,  fat: 5,   fiber: 5 } },
  { id: 'iv3',  name: 'Baingan Bharta',              servingSize: 200, servingUnit: 'g', imageQuery: 'baingan bharta roasted eggplant',nutrients: { calories: 130, protein: 4, carbs: 18,  fat: 5,   fiber: 5 } },
  { id: 'iv4',  name: 'Bhindi Masala (Okra)',        servingSize: 200, servingUnit: 'g', imageQuery: 'bhindi masala okra curry',    nutrients: { calories: 140, protein: 3,  carbs: 18,  fat: 6,   fiber: 5 } },
  { id: 'iv5',  name: 'Palak Paneer',                servingSize: 200, servingUnit: 'g', imageQuery: 'palak paneer spinach cheese', nutrients: { calories: 280, protein: 14, carbs: 12,  fat: 20,  fiber: 4 } },
  { id: 'iv6',  name: 'Matar Paneer',                servingSize: 200, servingUnit: 'g', imageQuery: 'matar paneer peas curry',     nutrients: { calories: 290, protein: 13, carbs: 18,  fat: 19,  fiber: 4 } },
  { id: 'iv7',  name: 'Shahi Paneer',                servingSize: 200, servingUnit: 'g', imageQuery: 'shahi paneer royal gravy',    nutrients: { calories: 350, protein: 14, carbs: 16,  fat: 26,  fiber: 2 } },
  { id: 'iv8',  name: 'Kadai Paneer',                servingSize: 200, servingUnit: 'g', imageQuery: 'kadai paneer wok cooked',     nutrients: { calories: 310, protein: 14, carbs: 14,  fat: 22,  fiber: 3 } },
  { id: 'iv9',  name: 'Butter Paneer Masala',        servingSize: 200, servingUnit: 'g', imageQuery: 'paneer butter masala curry',  nutrients: { calories: 360, protein: 14, carbs: 18,  fat: 26,  fiber: 2.5 } },
  { id: 'iv10', name: 'Jeera Aloo',                  servingSize: 200, servingUnit: 'g', imageQuery: 'jeera aloo cumin potato',     nutrients: { calories: 210, protein: 4,  carbs: 36,  fat: 6,   fiber: 4 } },
  { id: 'iv11', name: 'Lauki Sabzi (Bottle Gourd)',  servingSize: 200, servingUnit: 'g', imageQuery: 'lauki bottle gourd vegetable',nutrients: { calories: 85,  protein: 2,  carbs: 14,  fat: 2.5, fiber: 3 } },
  { id: 'iv12', name: 'Karela (Bitter Gourd)',       servingSize: 150, servingUnit: 'g', imageQuery: 'karela bitter gourd stir fry',nutrients: { calories: 90,  protein: 2,  carbs: 13,  fat: 3,   fiber: 4 } },
  { id: 'iv13', name: 'Methi Sabzi (Fenugreek)',     servingSize: 150, servingUnit: 'g', imageQuery: 'methi sabzi fenugreek leaves',nutrients: { calories: 100, protein: 4,  carbs: 12,  fat: 4,   fiber: 3.5 } },
  { id: 'iv14', name: 'Mushroom Masala',             servingSize: 200, servingUnit: 'g', imageQuery: 'mushroom masala curry india', nutrients: { calories: 160, protein: 6,  carbs: 14,  fat: 9,   fiber: 3 } },
  { id: 'iv15', name: 'Mixed Veg Curry',             servingSize: 200, servingUnit: 'g', imageQuery: 'mixed vegetable curry india', nutrients: { calories: 150, protein: 5,  carbs: 22,  fat: 5,   fiber: 5 } },

  // ── Non-Veg Dishes ────────────────────────────────────────────────────────
  { id: 'in1',  name: 'Chicken Curry',               servingSize: 200, servingUnit: 'g', imageQuery: 'chicken curry indian spicy',  nutrients: { calories: 250, protein: 22, carbs: 10,  fat: 14,  fiber: 2 } },
  { id: 'in2',  name: 'Butter Chicken (Murgh Makhani)',servingSize:200,servingUnit: 'g', imageQuery: 'butter chicken murgh makhani',nutrients: { calories: 310, protein: 22, carbs: 14,  fat: 18,  fiber: 2 } },
  { id: 'in3',  name: 'Chicken Tikka Masala',        servingSize: 200, servingUnit: 'g', imageQuery: 'chicken tikka masala creamy', nutrients: { calories: 280, protein: 23, carbs: 12,  fat: 16,  fiber: 2 } },
  { id: 'in4',  name: 'Chicken Tikka',               servingSize: 150, servingUnit: 'g', imageQuery: 'chicken tikka grilled india', nutrients: { calories: 250, protein: 28, carbs: 8,   fat: 12,  fiber: 1 } },
  { id: 'in5',  name: 'Tandoori Chicken',            servingSize: 150, servingUnit: 'g', imageQuery: 'tandoori chicken red spiced', nutrients: { calories: 230, protein: 29, carbs: 5,   fat: 10,  fiber: 0.5 } },
  { id: 'in6',  name: 'Mutton Curry',                servingSize: 200, servingUnit: 'g', imageQuery: 'mutton curry goat india',     nutrients: { calories: 320, protein: 25, carbs: 8,   fat: 20,  fiber: 1.5 } },
  { id: 'in7',  name: 'Egg Curry',                   servingSize: 200, servingUnit: 'g', imageQuery: 'egg curry indian masala',     nutrients: { calories: 230, protein: 14, carbs: 10,  fat: 15,  fiber: 2 } },
  { id: 'in8',  name: 'Keema Matar',                 servingSize: 200, servingUnit: 'g', imageQuery: 'keema matar minced meat peas',nutrients: { calories: 310, protein: 24, carbs: 14,  fat: 18,  fiber: 3 } },
  { id: 'in9',  name: 'Fish Curry (Indian style)',   servingSize: 200, servingUnit: 'g', imageQuery: 'fish curry indian spicy',     nutrients: { calories: 220, protein: 22, carbs: 8,   fat: 11,  fiber: 1.5 } },

  // ── Street Food & Snacks ──────────────────────────────────────────────────
  { id: 'is1',  name: 'Samosa (1 piece)',             servingSize: 90,  servingUnit: 'g', imageQuery: 'samosa fried indian snack',   nutrients: { calories: 260, protein: 5,  carbs: 34,  fat: 12,  fiber: 3 } },
  { id: 'is2',  name: 'Kachori (1 piece)',            servingSize: 80,  servingUnit: 'g', imageQuery: 'kachori fried pastry india',  nutrients: { calories: 250, protein: 5,  carbs: 30,  fat: 12,  fiber: 2 } },
  { id: 'is3',  name: 'Pakora (Mixed, 5 pieces)',    servingSize: 100, servingUnit: 'g', imageQuery: 'pakora fritters indian snack', nutrients: { calories: 310, protein: 7,  carbs: 35,  fat: 15,  fiber: 3 } },
  { id: 'is4',  name: 'Vada Pav',                    servingSize: 150, servingUnit: 'g', imageQuery: 'vada pav mumbai street food', nutrients: { calories: 320, protein: 8,  carbs: 48,  fat: 11,  fiber: 3.5 } },
  { id: 'is5',  name: 'Pav Bhaji',                   servingSize: 300, servingUnit: 'g', imageQuery: 'pav bhaji mumbai street',     nutrients: { calories: 420, protein: 10, carbs: 62,  fat: 14,  fiber: 6 } },
  { id: 'is6',  name: 'Bhel Puri',                   servingSize: 150, servingUnit: 'g', imageQuery: 'bhel puri indian chaat',      nutrients: { calories: 175, protein: 4,  carbs: 30,  fat: 4.5, fiber: 3 } },
  { id: 'is7',  name: 'Pani Puri (6 pieces)',        servingSize: 120, servingUnit: 'g', imageQuery: 'pani puri golgappa india',    nutrients: { calories: 200, protein: 4,  carbs: 35,  fat: 5,   fiber: 2 } },
  { id: 'is8',  name: 'Aloo Chaat',                  servingSize: 200, servingUnit: 'g', imageQuery: 'aloo chaat potato street',    nutrients: { calories: 240, protein: 5,  carbs: 42,  fat: 6,   fiber: 4 } },
  { id: 'is9',  name: 'Dahi Puri (6 pieces)',        servingSize: 150, servingUnit: 'g', imageQuery: 'dahi puri curd puri india',   nutrients: { calories: 230, protein: 6,  carbs: 36,  fat: 6,   fiber: 2 } },
  { id: 'is10', name: 'Chole Bhature',               servingSize: 350, servingUnit: 'g', imageQuery: 'chole bhature punjabi',       nutrients: { calories: 620, protein: 18, carbs: 82,  fat: 22,  fiber: 10 } },
  { id: 'is11', name: 'Misal Pav',                   servingSize: 300, servingUnit: 'g', imageQuery: 'misal pav maharashtra',       nutrients: { calories: 430, protein: 15, carbs: 64,  fat: 12,  fiber: 8 } },

  // ── Indian Sweets & Desserts ───────────────────────────────────────────────
  { id: 'iw1',  name: 'Gulab Jamun (2 pieces)',      servingSize: 80,  servingUnit: 'g', imageQuery: 'gulab jamun sweet india',     nutrients: { calories: 280, protein: 4,  carbs: 50,  fat: 8,   fiber: 0.5 } },
  { id: 'iw2',  name: 'Rasgulla (2 pieces)',         servingSize: 100, servingUnit: 'g', imageQuery: 'rasgulla bengali sweet',      nutrients: { calories: 180, protein: 4,  carbs: 38,  fat: 1,   fiber: 0 } },
  { id: 'iw3',  name: 'Jalebi',                      servingSize: 80,  servingUnit: 'g', imageQuery: 'jalebi orange sweet india',   nutrients: { calories: 290, protein: 2,  carbs: 60,  fat: 6,   fiber: 0.5 } },
  { id: 'iw4',  name: 'Gajar Halwa (Carrot Halwa)', servingSize: 100, servingUnit: 'g', imageQuery: 'gajar halwa carrot dessert',  nutrients: { calories: 260, protein: 4,  carbs: 40,  fat: 10,  fiber: 2 } },
  { id: 'iw5',  name: 'Kheer (Rice Pudding)',        servingSize: 150, servingUnit: 'g', imageQuery: 'kheer rice pudding india',    nutrients: { calories: 220, protein: 5,  carbs: 38,  fat: 6,   fiber: 0.5 } },

  // ── Indian Fruits ─────────────────────────────────────────────────────────
  { id: 'if1',  name: 'Guava (Amrood)',              servingSize: 100, servingUnit: 'g', imageQuery: 'guava tropical fruit',        nutrients: { calories: 68,  protein: 2.6,carbs: 14,  fat: 1,   fiber: 5.4 } },
  { id: 'if2',  name: 'Papaya',                      servingSize: 150, servingUnit: 'g', imageQuery: 'papaya tropical fruit',       nutrients: { calories: 65,  protein: 0.7,carbs: 16,  fat: 0.4, fiber: 2.5 } },
  { id: 'if3',  name: 'Pomegranate (Anar)',          servingSize: 100, servingUnit: 'g', imageQuery: 'pomegranate seeds fruit',     nutrients: { calories: 83,  protein: 1.7,carbs: 19,  fat: 1.2, fiber: 4 } },
  { id: 'if4',  name: 'Chikoo (Sapodilla)',          servingSize: 100, servingUnit: 'g', imageQuery: 'chikoo sapodilla fruit',      nutrients: { calories: 83,  protein: 0.4,carbs: 20,  fat: 1.1, fiber: 5 } },
  { id: 'if5',  name: 'Jackfruit (Kathal)',          servingSize: 150, servingUnit: 'g', imageQuery: 'jackfruit tropical india',    nutrients: { calories: 95,  protein: 2,  carbs: 23,  fat: 0.6, fiber: 2.5 } },
  { id: 'if6',  name: 'Mango',                       servingSize: 165, servingUnit: 'g', imageQuery: 'mango tropical fruit india',  nutrients: { calories: 99,  protein: 1.4,carbs: 25,  fat: 0.6, fiber: 2.6 } },
  { id: 'if7',  name: 'Banana',                      servingSize: 118, servingUnit: 'g', imageQuery: 'banana fruit yellow',         nutrients: { calories: 105, protein: 1.3,carbs: 27,  fat: 0.4, fiber: 3.1 } },
  { id: 'if8',  name: 'Watermelon',                  servingSize: 200, servingUnit: 'g', imageQuery: 'watermelon slice fresh',      nutrients: { calories: 60,  protein: 1.2,carbs: 15,  fat: 0.3, fiber: 0.8 } },
  { id: 'if9',  name: 'Grapes',                      servingSize: 100, servingUnit: 'g', imageQuery: 'grapes bunch fresh',          nutrients: { calories: 69,  protein: 0.7,carbs: 18,  fat: 0.2, fiber: 0.9 } },

  // ── Common items kept from original ───────────────────────────────────────
  { id: 'f10', name: 'Oatmeal (cooked)',             servingSize: 150, servingUnit: 'g', imageQuery: 'oatmeal breakfast bowl',      nutrients: { calories: 100, protein: 4,  carbs: 18,  fat: 2,   fiber: 3 } },
  { id: 'f13', name: 'Whole Wheat Bread',            servingSize: 30,  servingUnit: 'g', imageQuery: 'whole wheat bread slice',     nutrients: { calories: 80,  protein: 4,  carbs: 14,  fat: 1,   fiber: 2 } },
  { id: 'f16', name: 'Sweet Potato (baked)',         servingSize: 130, servingUnit: 'g', imageQuery: 'sweet potato baked',          nutrients: { calories: 115, protein: 2,  carbs: 27,  fat: 0,   fiber: 4 } },
  { id: 'f20', name: 'Apple',                        servingSize: 182, servingUnit: 'g', imageQuery: 'apple red fruit',             nutrients: { calories: 95,  protein: 0.5,carbs: 25,  fat: 0.3, fiber: 4.4 } },
  { id: 'f21', name: 'Orange',                       servingSize: 131, servingUnit: 'g', imageQuery: 'orange citrus fruit',         nutrients: { calories: 62,  protein: 1.2,carbs: 15,  fat: 0.2, fiber: 3.1 } },
  { id: 'f30', name: 'Broccoli (steamed)',           servingSize: 100, servingUnit: 'g', imageQuery: 'steamed broccoli vegetable',  nutrients: { calories: 35,  protein: 2.4,carbs: 7,   fat: 0.4, fiber: 3.3 } },
  { id: 'f31', name: 'Spinach (cooked)',             servingSize: 100, servingUnit: 'g', imageQuery: 'cooked spinach palak',        nutrients: { calories: 23,  protein: 3,  carbs: 3.6, fat: 0.3, fiber: 2.4 } },
  { id: 'f50', name: 'Almonds',                      servingSize: 28,  servingUnit: 'g', imageQuery: 'almonds nuts dry fruits',     nutrients: { calories: 164, protein: 6,  carbs: 6,   fat: 14,  fiber: 3.5 } },
  { id: 'f51', name: 'Peanuts / Groundnuts',         servingSize: 28,  servingUnit: 'g', imageQuery: 'peanuts groundnuts india',    nutrients: { calories: 166, protein: 7.5,carbs: 5,   fat: 14,  fiber: 2.4 } },
  { id: 'f70', name: 'Protein Bar',                  servingSize: 60,  servingUnit: 'g', imageQuery: 'protein bar fitness snack',   nutrients: { calories: 210, protein: 20, carbs: 22,  fat: 7,   fiber: 3 } },
];
